#define HD_DEBUG
#define HD_TEST
#define HD_OPTIMIZED
#define PIXEL_COUNT 919
#define PIXEL_PIN 14
#define BUTTON_PIN 26
#define INTER_MAX_LIGHTS 20
#define EMITTER_MAX_LIGHTS 100
#define EMITTER_MIN_SPEED 0.05f
#define EMITTER_MAX_SPEED 5.f
#define EMITTER_MIN_LENGTH 10
#define EMITTER_MAX_LENGTH 30
#define EMITTER_MIN_LIFE 120
#define EMITTER_MAX_LIFE 1440
#define EMITTER_MIN_BRI 0.75f
#define EMITTER_MAX_BRI 1.0f
#define MAX_PORTS 90 // 85
#define NUM_MODELS 4
#define MAX_LIGHT_LISTS 20
#define MAX_BRIGHTNESS 255
#define MAX_CONDITIONAL_WEIGHTS 10
#define MAX_OUTGOING_LIGHTS 10
